version: '3.7'
services:
  frontend:
    build: ./transactions-front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    network_mode: "host"
  api:
    build: .
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    network_mode: "host"
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    network_mode: "host"
