spring.data.mongodb.uri: mongodb://192.168.1.19:27017/transactions

server:
  port: 9001

spring:
  batch:
    initializer:
      enabled: false
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:transactionsBatch;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: true
    h2:
      console:
        enable: true
