spring.data.mongodb.uri: mongodb://localhost:27017/transactions

server:
  port: 9001


spring:
  application:
    name: transactions-cnab
  batch:
    jdbc:
      initialize-schema: ALWAYS
    initializer:
      enabled: false
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactions?createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      poolName: Hikari
      auto-commit: true
    h2:
      console:
        enable: true
